name: CI service

on:
  workflow_call:
    inputs:
      context_path:
        required: true
        type: string
      enable-snyk:
        required: false
        type: boolean
        default: true


jobs:
  nx-ci:
    uses: ./.github/workflows/nx-ci.yaml
    secrets:  inherit
    with:
      context_path: ${{ inputs.context_path }}

  snyk:
    if: ${{ inputs.enable-snyk }}
    uses: ./.github/workflows/snyk-sast-node.yaml
    secrets:  inherit

  sonar:
    if: ${{ inputs.enable-sonar }}
    uses: ./.github/workflows/sonar-sast-client.yaml
    secrets:  inherit
    with:
      context_path: ${{ inputs.context_path }}