name: CI service

on:
  workflow_call:
    inputs:
      solution_file:
        required: true
        type: string
      dockerfile_path:
        required: true
        type: string
      build-args:
        type: string
        description: "List of build-time variables"
        required: false
      service_name:
        required: true
        type: string
      context_path:
        required: true
        type: string
      aws_ci_region:
        type: string
        default: "us-east-1"
      aws_ci_account:
        type: string
        default: "479886561928"
      enable-snyk:
        required: false
        type: boolean
        default: true
      enable-sonar:
        required: false
        type: boolean
        default: true
      enable-resharper:
        required: false
        type: boolean
        default: true
      enable-ecr:
        required: false
        type: boolean
        default: true
      enable-jfrog:
        required: false
        type: boolean
        default: false

permissions:
  contents: read

jobs:
  test:
    uses: ./.github/workflows/dotnet-build-test.yaml
    secrets:  inherit
    with:
      context_path: ${{ inputs.context_path }}

  sonar:
    if: ${{ inputs.enable-sonar }}
    uses: ./.github/workflows/sonar-sast.yaml
    secrets:  inherit
    with:
      solution_file: ${{ inputs.solution_file }}
      context_path: ${{ inputs.context_path }}
      
  snyk:
    if: ${{ inputs.enable-snyk }}
    uses: ./.github/workflows/snyk-sast.yaml
    secrets:  inherit
    with:
      solution_file: ${{ inputs.solution_file }}
      context_path: ${{ inputs.context_path }}

  resharper:
    if: ${{ inputs.enable-resharper }}
    uses: ./.github/workflows/resharper.yaml
    secrets:  inherit
    with:
      solution_file: ${{ inputs.solution_file }}
      context_path: ${{ inputs.context_path }}

  build-push-ecr:
    if: ${{ inputs.enable-ecr }}
    uses: ./.github/workflows/aws-ecr.yaml
    secrets:  inherit
    needs: test
    with:
      context_path: ${{ inputs.context_path }}
      aws_ci_region: ${{ inputs.aws_ci_region }}
      aws_ci_account: ${{ inputs.aws_ci_account }}
      service_name: ${{ inputs.service_name }}
      dockerfile_path: ${{ inputs.dockerfile_path }}

  helm-publish:
    uses: ./.github/workflows/aws-helm-publish.yaml
    secrets:  inherit
    needs: build-push-ecr
    with:
      aws_ci_region: ${{ inputs.aws_ci_region }}

  build-push-jfrog:
    if: ${{ inputs.enable-jfrog }}
    uses: ./.github/workflows/jfrog-docker.yaml
    secrets:  inherit
    needs: test
    with:
      context_path: ${{ inputs.context_path }}
      service_name: ${{ inputs.service_name }}


    