name: Snyk SAST

on:
  workflow_call:
   inputs:
      upload-to-github-code-scanning:
        required: false
        type: boolean
        default: false

permissions:
  contents: read
  
jobs:
  snyk:
    name: Run Snyk to check for vulnerabilitie
    runs-on: ubuntu-latest    
    permissions:
      contents: read
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: ${{ inputs.upload-to-github-code-scanning }} # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high --all-projects --sarif-file-output=snyk.sarif
      - name: Upload result to GitHub Code Scanning
        if: ${{ inputs.upload-to-github-code-scanning }}
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
